# provider
deployRegion: us-west-2
profile: takanorig
runtime: python3.8

# properties
properties:
  retentionInDays: 3

# serverless-python-requirements
pythonRequirements:
  fileName: ../requirements.txt

# serverless-prune-plugin
prune:
  automatic: true
  number: 3

# Cognito settings
cognito:
  userPool: example-serverless-cognito-dev-pool
